### ISSUE TITLE
the parent pom is not found if a project depends on the snapshot version

### ISSUE THREAD

**Issue by alexlehm** [vert-x3/vertx-parent#1]
the projects that references the parent pom as snapshot version do not work if the file was not installed locally before. This is because the snapshot file is not found if it is not already added (the pom references sonatype as parent, but we never get to that point).
it would be better to either release the pom as version or to put the sonatype repository into each pom that uses the snapshot version.

**Comment by vietj** [comment]
we don't use snapshots anymore for parents.
