### ISSUE TITLE
Use jar-no-fork and test-jar-no-fork goals instead of jar and test-jar for maven-source-plugin

### ISSUE THREAD

**Issue by vietj** [vert-x3/vertx-parent#13]

**Comment by tsegismont** [comment]
Out of curiosity, what's the motivation for this?

**Comment by jponge** [comment]
@vietj Like @tsegismont I'm curious

**Comment by vietj** [comment]
the _jar_ goal runs a new maven lifecycle and thus the _bsc_ plugin is executed again during the _package_ phase, this plugin is already executed in the _generate-source_ phase.

see https://gist.github.com/vietj/c3d6e95b0eee2f15d92e4ed68070e5ed (in verbose mode though)

so it makes simply the build faster and less verbose.
