### ISSUE TITLE
Error running tests with vertx-parent 6

### ISSUE THREAD

**Issue by sisqbates** [vert-x3/vertx-parent#7]
When running tests from maven using vertx-ext-parent v15 (which depends on vertx-parent v6), I'm getting an error:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18:test (default-test) on project vertx-cassandra-client: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.18:test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /Users/ferran/feina/oss/vertx/vertx-cassandra/vertx-cassandra-client && /Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/bin/java '${argLine}' -server -Xmx1200M -jar /Users/ferran/feina/oss/vertx/vertx-cassandra/vertx-cassandra-client/target/surefire/surefirebooter6787365219451412939.jar /Users/ferran/feina/oss/vertx/vertx-cassandra/vertx-cassandra-client/target/surefire/surefire6045587325000177173tmp /Users/ferran/feina/oss/vertx/vertx-cassandra/vertx-cassandra-client/target/surefire/surefire_08488067062760839950tmp
```

The project is built successfully when setting the parent to vertx-ext-parent v14. 

Comparing the output in execution, I see that the command to run the tests with that version is slightly different

```

Forking command line: /bin/sh -c cd /Users/ferran/feina/oss/vertx/vertx-cassandra/vertx-cassandra-client && /Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/bin/java -server -Xmx1200M -jar /Users/ferran/feina/oss/vertx/vertx-cassandra/vertx-cassandra-client/target/surefire/surefirebooter3451854156585741543.jar /Users/ferran/feina/oss/vertx/vertx-cassandra/vertx-cassandra-client/target/surefire/surefire1083980854613232452tmp /Users/ferran/feina/oss/vertx/vertx-cassandra/vertx-cassandra-client/target/surefire/surefire_03065961154113509632tmp
```

I've been investigating the changes in both vertx-parent and vertx-ext-parent, and seems that the fix for #5 could be related, since seems to introduce ``${argLine}``in the command line.

**Comment by cescoffier** [comment]
`argLine` should be empty in your case no ?

Could you try to add the maven surefire plugin in your `pom.xml` file to see if it fixes the issue.

**Comment by sisqbates** [comment]
Mmm... seems like my fault: I have a parent/child project (
https://github.com/sisqbates/vertx-cassandra) and I changed the parent
version without updating the child reference. Once synchronized everyting
seems to work fine.

Feel free to close the issue...

Sorry for the noise!


El 7:48 dc. 01/07/2015 Clement Escoffier <notifications@github.com> va
escriure:

**Comment by cescoffier** [comment]
Close as requested.
