### ISSUE TITLE
${argLine} problems

### ISSUE THREAD

**Issue by sisqbates** [vert-x3/vertx-parent#8]
A couple of days ago I opened #7 because I experienced problems running tests when a project inherited from vertx-parent version 6. I suggested to close the issue because I thought it was my mistake, but now the problems are happening again.

I've set up a simple reproducer which causes the error at `sisqbates/vertx-parent-issue`. Running `mvn clean test` on the fresh clone triggers the error, while editing pom.xml and uncommenting the surefire plugin config (which is identical to the one in vertx-parent version 6 without ${argLine}) does not.

**Comment by cescoffier** [comment]
https://github.com/vert-x3/vertx-parent/pull/10 fixes the issue.
